### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by iomz** [Interactions-HSG/uArm-Controller#13]
This firmware for uArm-Controller has become rich enough and it should provide its version.
Ultimately each driver would better be compliant with micro versioning, but this might be too tangled, so I propose to add "`Version`" `request_type` for the `Request` message that simply returns the firmware version.

**Comment by jo-bru** [comment]
To handle similar MCU specific requests, I've added an MCU driver.  Now, a profile for the MCU itself can be created and registered to handle requests such as getting the firmware version, getting the used RAM space, reset the MCU (without using the reset button), etc.
For this, I've created the new branch `dev/mcu-driver`. I'm not sure if the RAM space measurement works correctly, but for now, it was just to illustrate another use-case for the MCU driver. (see commit d37df3e)


Should I open a pull request to merge this feature to the main branch? 
And should such a small feature be implemented in a separate branch or should I do it directly in the main branch next time?

**Comment by iomz** [comment]
Although it is a smart idea to put it in `src/drivers`, it's a bit weird for me to call it "MCU driver" as this "uArm Controller" has a specific hardware dependency (ATMega2560+uFactory controller board), and also other "drivers" are for peripherals – the firmware version/SRAM usage/soft reset should reside one level higher than those. It might be less confusing if you put the content of `mcu_driver.[c|h]` in `main.[c|h]`. Just sayin'.

>Should I open a pull request to merge this feature to the main branch?

Yes, always.

>And should such a small feature be implemented in a separate branch or should I do it directly in the main branch next time?

Ideally, one branch would better correspond to one issue. Direct commit to the main branch might be appropriate if it's a trivial update on documentation/project configuration or the repo is maintained by a single author.

**Comment by jo-bru** [comment]
Yes, I see your point. I think we have to further discuss how profiles for integrated parts (e.g. MCU, OLED display, rotary potentiometer, etc.) are handled in the firmware as well as in the gateway implementation.
