### ISSUE TITLE
New profile ("activation") type for actuators?

### ISSUE THREAD

**Issue by iomz** [Interactions-HSG/uArm-Controller#5]
"Polling" is a term often used for data access to/from passive entities (e.g., sensors), but actually LEDs are "actuators" like robots and their state are not affected by the environment, but the actions – we may need to create the forth type: "actuator"...
Let's discuss this on Wed.

_Originally posted by @iomz in https://github.com/Interactions-HSG/uArm-Controller/pull/4#discussion_r503667361_

**Comment by jo-bru** [comment]
Question: Do profiles with "actuators" type send feedback after the action is completed?
(e.g. if the red LED is turned on, should the MCU send a feedback message to the gateway?)

**Answer:** Yes, always send feedback on a successful action.

**Comment by iomz** [comment]
Just for the side note to come back later; about the name of the profile "activation type", probably we can employ this vocabulary from gRPC:
https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-life-cycle

Unary/[Server|Client] Streaming/etc... I guess we'll know if it's good or not when we start synchronizing this nanopb with gRPC gateway.
