### ISSUE TITLE
Create protobuf_helper module with callback functions + pb initialization

### ISSUE THREAD

**Issue by jo-bru** [Interactions-HSG/uArm-Controller#6]
To be able to encode/decode pb message fields with a dynamic length (e.g. String), [callback functions](https://jpa.kapsi.fi/nanopb/docs/concepts.html#field-callbacks) for each field have to be implemented.
I suggest creating a protobuf_helper module (protobuf_helper.cpp + protobuf_helper.h) which contains initialization functions and all callback functions to keep the code manageable.

Use the following example codes as a starting point:
[encode_callbacks.c](https://github.com/nanopb/nanopb/blob/master/tests/callbacks/encode_callbacks.c)
[decode_callbacks.c](https://github.com/nanopb/nanopb/blob/master/tests/callbacks/decode_callbacks.c)

**Comment by jo-bru** [comment]
Since callbacks inside `oneof` messages are complex to handle, for now, string/data fields inside `request` messages are defined with a fixed maximum length in the .proto file. 
To handle callbacks inside a  `oneof` message see [New features in nanopb0.4: Message level callback for oneofs](https://jpa.kapsi.fi/nanopb/docs/whats_new.html#message-level-callback-for-oneofs)

**Comment by iomz** [comment]
Ok, thanks for the heads-up.
