### ISSUE TITLE
Extend the automatic driver initialization (Makefile: add_driver) 

### ISSUE THREAD

**Issue by jo-bru** [Interactions-HSG/uArm-Controller#8]
To simplify the driver implementation, the automatic driver initialization must be further extended, so that appropriate sections are added in the following files:

- `line_protocol.proto`: messages for R_Template_Driver + A_Template_Driver (+ Response messages?)

-  `action_handler()` in main.cpp: add case for new driver

- `registration_handler()` in main.cpp: add case for new driver

- include driver.h files in main.cpp

- (callback functions in protobuf_handler: only used if dynamic fields are used in message)

**Comment by iomz** [comment]
It depends on #6.

**Comment by jo-bru** [comment]
The automatic driver initialization was completed with the latest [commit](https://github.com/Interactions-HSG/uArm-Controller/commit/80c3c21e1b6044163ccdddf132cb7c1a3a49d455) made on branch `dev/event-handler`.
